version: "3.2"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - PORT=3000
